Markets:
  blackmarket:
    discount percentage: 50
    chance to use in blackmarket: 25
  items:
    header lore:
      - "&e&l${amount}"
      - "&eClick to purchase!"
      - " "

# Customize the appearance of the guis
guis:
  marketplace:
    window name: "&2&lMarketplace"
    structure:
      - "1 1 1 1 1 1 1 1 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "< 1 1 1 1 1 1 1 >"
    ingredients:
      '1':
        name: " "
        material: BLACK_STAINED_GLASS_PANE
      '<':
        tag: "BACK"
        name: "&cPrevious Page"
        material: REDSTONE_BLOCK
      '>':
        tag: "NEXT"
        name: "&cNext Page"
        material: EMERALD_BLOCK
  blackmarket:
    window name: "&7&lBlackmarket"
    structure:
      - "1 1 1 1 1 1 1 1 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "1 . . . . . . . 1"
      - "1 1 1 1 1 1 1 1 1"
    ingredients:
      '1':
        name: " "
        material: BLACK_STAINED_GLASS_PANE
  confirmation:
    window name: "&cClick To Confirm"
    structure:
      - "1 1 1 1 1 1 1 1 1"
      - "1 . A . I . D . 1"
      - "1 1 1 1 1 1 1 1 1"
    ingredients:
      '1':
        name: " "
        material: BLACK_STAINED_GLASS_PANE
      'I':
        tag: "ITEM_TO_CONFIRM" # Tag states that it will revert to the item they are buying
        name: "&2Loading Item..."
        material: "GREEN_STAINED_GLASS_PANE"
      'A':
        tag: "ACCEPT" # Tag states that it will accept the transaction
        name: "&2Confirm"
        material: "GREEN_STAINED_GLASS_PANE"
      'D':
        tag: "DENY" # Tag states that it will deny the transaction
        name: "&cDeny"
        material: "RED_STAINED_GLASS_PANE"

# Messages used in-game
messages:
  commands:
    insufficient permissions: "&cYou do not have permission to use this!"
    requires player: "&cOnly players can use this!"

    sell:
      description: "Add your current held item to the marketplace."
      success: "&2Your item &e[{name}&7x&e{amount}] &2has been listed on the market!"
      failure:
        invalid item: "&cThis item cannot be sold!"
        invalid price: "&cPrice of ${amount} is not permitted!"

    marketplace:
      description: "View the marketplace."
      success: "&2Opening marketplace...!"

    blackmarket:
      description: "View the hidden underbelly of the marketplace... With dirt cheap prices!"
      success: "&7Opening marketplace...!"

    transactions:
      description: "View a player's transaction history."
      success:
        transaction_line: "  &7- &2{material}x{amount} sold for {amount}"
        full_format: |
          =-=-=-=-=-=-=-=-=-=-=-=-=-=
          &e&n{player}'s History:
          {transaction_lines}
          =-=-=-=-=-=-=-=-=-=-=-=-=-=